/**
 * Names of every component exported from the package root.
 * Consumed by the Vue plugin (global registration) and the Nuxt module
 * (auto-imports). Keep in sync with `src/components/index.ts`.
 */
export const componentNames = [
  'Accordion',
  'Alert',
  'App',
  'AppShell',
  'AspectRatio',
  'AuthProviders',
  'Avatar',
  'AvatarGroup',
  'Badge',
  'BarChart',
  'Banner',
  'Breadcrumb',
  'Button',
  'ButtonGroup',
  'Calendar',
  'Card',
  'Carousel',
  'ChartLegend',
  'Checkbox',
  'ColorPicker',
  'Combobox',
  'Collapsible',
  'CommandPalette',
  'Container',
  'ConfirmDialog',
  'ContextMenu',
  'DateField',
  'DatePicker',
  'DateRangePicker',
  'DescriptionList',
  'Dialog',
  'DonutChart',
  'Drawer',
  'DropdownMenu',
  'Editable',
  'EmptyState',
  'FileUpload',
  'Form',
  'FormField',
  'HoverCard',
  'Icon',
  'Input',
  'Kbd',
  'Label',
  'LineChart',
  'NavigationMenu',
  'NumberInput',
  'Menubar',
  'PageHeader',
  'Pagination',
  'PasswordInput',
  'PinInput',
  'Popover',
  'Progress',
  'RadioGroup',
  'Rating',
  'ScrollArea',
  'ScrollFade',
  'Select',
  'Separator',
  'Sidebar',
  'SignaturePad',
  'Skeleton',
  'Slider',
  'Sparkline',
  'Splitter',
  'Stat',
  'Stepper',
  'Switch',
  'Table',
  'Tabs',
  'TagsInput',
  'Textarea',
  'Toaster',
  'Toggle',
  'ToggleGroup',
  'TimeField',
  'Timeline',
  'Toolbar',
  'Tooltip',
  'Tree',
] as const

export type ComponentName = (typeof componentNames)[number]

/**
 * Names of every block exported from `iryx-ui/marketing`.
 * A list of strings rather than the modules themselves, because the Nuxt module
 * runs at build time and must not pull `.vue` files into Node.
 * Keep in sync with `src/marketing/index.ts`.
 */
export const marketingComponentNames = [
  'BrowserFrame',
  'FeatureCard',
  'Hero',
  'PricingCard',
  'PricingTable',
  'Section',
  'SiteFooter',
  'SiteHeader',
  'TestimonialCard',
] as const

export type MarketingComponentName = (typeof marketingComponentNames)[number]
