/**
 * Names of every component exported from the package root.
 * Consumed by the Vue plugin (global registration) and the Nuxt module
 * (auto-imports). Keep in sync with `src/components/index.ts`.
 */
export const componentNames = [
  'Alert',
  'App',
  'AppShell',
  'Badge',
  'BarChart',
  'Banner',
  'Breadcrumb',
  'Button',
  'ButtonGroup',
  'Card',
  'ChartLegend',
  'Checkbox',
  'Combobox',
  'Container',
  'ConfirmDialog',
  'DatePicker',
  'DateRangePicker',
  'Dialog',
  'Drawer',
  'DropdownMenu',
  'EmptyState',
  'FileUpload',
  'Form',
  'FormField',
  'Input',
  'Label',
  'LineChart',
  'NavigationMenu',
  'NumberInput',
  'PageHeader',
  'Pagination',
  'PasswordInput',
  'Progress',
  'RadioGroup',
  'Select',
  'Separator',
  'Sidebar',
  'Skeleton',
  'Sparkline',
  'Stat',
  'Stepper',
  'Switch',
  'Table',
  'Tabs',
  'Textarea',
  'Toaster',
  'Tooltip',
] as const

export type ComponentName = (typeof componentNames)[number]
